# Generated by Django 5.2.14 on 2026-05-14 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_customer_gstin_invoice_cgst_amount_and_more'),
        ('core', '0002_business_alter_userprofile_role_userprofile_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='core.business'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.business'),
        ),
    ]
