# Generated by Django 5.2.14 on 2026-05-16 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_customer_business_invoice_business'),
        ('core', '0002_business_alter_userprofile_role_userprofile_business'),
        ('inventory', '0006_category_business_product_business_purchase_business_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='applied_offer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='original_unit_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='FestivalOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('discount_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount')], default='PERCENTAGE', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('apply_to_all', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority offers are applied first')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='core.business')),
                ('categories', models.ManyToManyField(blank=True, related_name='offers', to='inventory.category')),
                ('products', models.ManyToManyField(blank=True, related_name='offers', to='inventory.product')),
            ],
        ),
    ]
