# Generated by Django 5.2.14 on 2026-05-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_business_alter_userprofile_role_userprofile_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='festival_offer_enabled',
            field=models.BooleanField(default=False, help_text='Global toggle for Festival Offers'),
        ),
    ]
