# Generated by Django 5.2.14 on 2026-05-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hsn_code',
            field=models.CharField(blank=True, help_text='HSN/SAC Code for GST', max_length=20, null=True),
        ),
    ]
